name: "Destroy"
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      # Sets up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # Creates a Plan for the desired Terraform Configuration    
      - name: Terraform Init
        id: init
        run: terraform init
      # Destroy current Terraform configuration
      - name: Destroy Terraform
        run: terraform destroy -auto-approve
