name: "Terraform"
on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Destroy Terraform
        run: terraform destroy
